version: '3'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network2
    
  app:
    image: quarkus/quackus-jvm:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_USR: ${POSTGRES_USER}
      DB_PW: ${POSTGRES_PASSWORD}
      DB_URL: postgresql://db:5432/postgres
    volumes:
      - ./images:/deployments/images
    depends_on:
      - db
    networks:
      - db_network2

networks:
  db_network2:
    driver: bridge

volumes:
  pgdata:
